### ISSUE TITLE
Does search for encrypted Strings

### ISSUE THREAD

**Issue by DevX-Cipher** [miso-xyz/CajunSpice#1]
hi im not sure if you are still updating this but it does not search for encrypted strings ect

**Comment by DevX-Cipher** [comment]
Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\9Rays.Net\SpicesNet5\Bin\NRObfuscator'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at System.IO.File.ReadAllBytes(String path)
   at CajunSpice.Deobfuscator..ctor(String path)
   at CajunSpice.Program.Main(String[] args)

**Comment by miso-xyz** [comment]
This error is unrelated to CajunSpice.

You have to drag your sample onto the *.exe file, the sample HAS to be a valid dotNET Assembly file.
Samples cannot be folders.

If you were debugging, clear any starting arguments.
If you were not debugging, make sure your sample file can be reached with the given permissions (try running it as admin by making a shortcut, going into properties->Advanced and selecting "run as administrator", then adding your sample as an argument)

**Comment by miso-xyz** [comment]
This error is unrelated to CajunSpice.

You have to drag your sample onto the *.exe file, the sample HAS to be a valid dotNET Assembly file.
Samples cannot be folders.

If you were debugging, clear any starting arguments.
If you were not debugging, make sure your sample file can be reached with the given permissions (try running it as admin by making a shortcut, going into properties->Advanced and selecting "run as administrator", then adding your sample as an argument)

**Comment by DevX-Cipher** [comment]
yes i tried running it as admin as well put it into the same folder as the other files

**Comment by DevX-Cipher** [comment]
i downloaded the project but notice this exeception System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'C:\Users\Modz2014\Downloads\CajunSpice-main\bin\Debug\obf\ezPayCheckKeygen.exe'.'

**Comment by miso-xyz** [comment]
Might've left the debugging arguments in, go into the Project properties and clear out the debugging arguments.
